/** @type {import('stylelint').Config} */
export default {
  extends: [
    'stylelint-config-standard',
    '@stylistic/stylelint-config',
  ],
  plugins: [
    'stylelint-order',
    'stylelint-high-performance-animation',
    'stylelint-declaration-block-no-ignored-properties',
  ],
  rules: {
    'block-no-empty': true,
    'alpha-value-notation': 'number',
    'color-function-notation': 'legacy',
    'color-hex-length': 'long',
    'hue-degree-notation': 'angle',
    'custom-property-pattern': null,
    'font-family-no-missing-generic-family-keyword': null,
    'function-no-unknown': null,
    'length-zero-no-unit': true,
    'property-no-vendor-prefix': null,
    'property-no-deprecated': true,
    'media-type-no-deprecated': true,
    'selector-class-pattern': null,
    'selector-no-vendor-prefix': null,
    'selector-pseudo-class-no-unknown': [
      true,
      {
        ignorePseudoClasses: ['deep', 'global', 'slotted'],
      },
    ],
    'selector-pseudo-element-no-unknown': [
      true,
      {
        ignorePseudoElements: ['v-deep', 'v-global', 'v-slotted'],
      },
    ],
    'declaration-property-value-no-unknown': [
      true,
      {
        ignoreProperties: { '/.*/': String.raw`/v-bind\(.+\)/` },
      },
    ],
    'declaration-block-no-redundant-longhand-properties': [
      true,
      {
        ignoreShorthands: ['/flex/'],
      },
    ],
    'rule-empty-line-before': [
      'always',
      {
        except: ['first-nested'],
      },
    ],
    'max-nesting-depth': 10,
    'value-keyword-case': [
      'lower',
      {
        camelCaseSvgKeywords: true,
        ignoreFunctions: ['v-bind'],
      },
    ],
    'value-no-vendor-prefix': null,
    'no-empty-source': null,
    'no-duplicate-selectors': true,
    'no-descending-specificity': null,
    'no-invalid-position-declaration': null,
    'block-no-redundant-nested-style-rules': null,
    'nesting-selector-no-missing-scoping-root': null,
    'plugin/no-low-performance-animation-properties': [
      true,
      {
        ignoreProperties: [
          'color',
          'background-color',
          'background',
          'border-color',
          'border',
          'all',
          'margin',
          'width',
          'height',
          'visibility',
          'box-shadow',
        ],
      },
    ],
    'plugin/declaration-block-no-ignored-properties': true,
    '@stylistic/indentation': 2,
    '@stylistic/string-quotes': 'single',
    '@stylistic/selector-list-comma-newline-after': null,
    '@stylistic/max-line-length': null,
    '@stylistic/number-leading-zero': 'never',
    'order/order': [
      'custom-properties',
      'declarations',
    ],
    'order/properties-order': [
      'all',
      'content',
      'quotes',
      'counter-reset',
      'counter-increment',
      'resize',
      'position',
      'top',
      'right',
      'left',
      'bottom',
      'z-index',
      'display',
      'vertical-align',
      'visibility',
      'float',
      'clear',
      'overflow',
      'overflow-x',
      'overflow-y',
      'clip',
      'clip-path',
      'zoom',
      'columns',
      'column-count',
      'column-span',
      'column-fill',
      'column-width',
      'flex',
      'flex-grow',
      'flex-shrink',
      'flex-basis',
      'flex-flow',
      'flex-direction',
      'flex-wrap',
      'grid',
      'grid-template',
      'grid-template-rows',
      'grid-template-columns',
      'grid-template-areas',
      'grid-auto-rows',
      'grid-auto-columns',
      'grid-auto-flow',
      'grid-area',
      'grid-row',
      'grid-row-start',
      'grid-row-end',
      'grid-column',
      'grid-column-start',
      'grid-column-end',
      'gap',
      'grid-gap',
      'row-gap',
      'grid-row-gap',
      'column-gap',
      'grid-column-gap',
      'column-rule',
      'column-rule-width',
      'column-rule-style',
      'column-rule-color',
      'place-items',
      'align-items',
      'justify-content',
      'align-content',
      'align-self',
      'order',
      'box-sizing',
      'width',
      'min-width',
      'max-width',
      'height',
      'min-height',
      'max-height',
      'margin',
      'margin-x',
      'margin-y',
      'margin-top',
      'margin-right',
      'margin-bottom',
      'margin-left',
      'padding',
      'padding-x',
      'padding-y',
      'padding-top',
      'padding-right',
      'padding-left',
      'padding-bottom',
      'table-layout',
      'empty-cells',
      'caption-side',
      'border-spacing',
      'border-collapse',
      'list-style',
      'list-style-position',
      'list-style-type',
      'list-style-image',
      'stroke',
      'stroke-width',
      'fill',
      'color',
      'font',
      'font-family',
      'src',
      'font-variant',
      'font-size',
      'font-weight',
      'font-style',
      'font-size-adjust',
      'font-stretch',
      'font-effect',
      'font-emphasize',
      'font-emphasize-position',
      'font-emphasize-style',
      'font-smooth',
      'line-height',
      'text-align',
      'text-align-last',
      'white-space',
      'text-decoration',
      'text-emphasis',
      'text-emphasis-color',
      'text-emphasis-style',
      'text-emphasis-position',
      'text-indent',
      'text-justify',
      'letter-spacing',
      'word-spacing',
      'text-outline',
      'text-transform',
      'text-wrap',
      'text-overflow',
      'text-overflow-ellipsis',
      'text-overflow-mode',
      'text-shadow',
      'word-wrap',
      'word-break',
      'tab-size',
      'hyphens',
      'cursor',
      'user-select',
      'pointer-events',
      'nav-index',
      'nav-up',
      'nav-right',
      'nav-down',
      'nav-left',
      'background',
      'background-color',
      'background-image',
      'background-repeat',
      'background-attachment',
      'background-position',
      'background-position-x',
      'background-position-y',
      'background-clip',
      'background-origin',
      'background-size',
      'object-fit',
      'border',
      'border-width',
      'border-style',
      'border-color',
      'border-top',
      'border-top-width',
      'border-top-style',
      'border-top-color',
      'border-left',
      'border-left-width',
      'border-left-style',
      'border-left-color',
      'border-right',
      'border-right-width',
      'border-right-style',
      'border-right-color',
      'border-bottom',
      'border-bottom-width',
      'border-bottom-style',
      'border-bottom-color',
      'border-radius',
      'border-top-left-radius',
      'border-top-right-radius',
      'border-bottom-right-radius',
      'border-bottom-left-radius',
      'border-image',
      'border-image-source',
      'border-image-slice',
      'border-image-width',
      'border-image-outset',
      'border-image-repeat',
      'outline',
      'outline-width',
      'outline-style',
      'outline-color',
      'outline-offset',
      'opacity',
      'box-shadow',
      'box-decoration-break',
      'transition',
      'transition-duration',
      'transition-delay',
      'transition-timing-function',
      'transition-property',
      'transform',
      'transform-origin',
      'animation',
      'animation-name',
      'animation-duration',
      'animation-play-state',
      'animation-timing-function',
      'animation-delay',
      'animation-iteration-count',
      'animation-direction',
      'backface-visibility',
      'will-change',
      'filter',
    ],
  },
  overrides: [
    {
      files: [
        '**/*.(scss|css|html|vue)',
      ],
      extends: [
        'stylelint-config-standard-scss',
      ],
      customSyntax: 'postcss-scss',
      rules: {
        'scss/at-extend-no-missing-placeholder': null,
        'scss/at-mixin-pattern': null,
        'scss/at-function-pattern': null,
        'scss/dollar-variable-pattern': null,
      },
    },
    {
      files: [
        '**/*.(html|vue)',
      ],
      customSyntax: 'postcss-html',
    },
  ],
};
