name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Format check
        run: cargo fmt --manifest-path src-tauri/Cargo.toml --all -- --check

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: "pnpm"
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run typecheck
        run: pnpm run typecheck

      - name: Code js lint
        run: pnpm run lint:js

      - name: Code style lint
        run: pnpm run lint:styles
